### ISSUE TITLE
Group Capstone Project - Set up your Kanban Board

### ISSUE THREAD

**Issue by tafaramafemba** [Alexr16/Pokemon-profiles-capstone#21]
### Group Details
Number of group members: 2
Names: Tafara Mafemba and Jorge Rios

### Project Link
[https://github.com/Alexr16/Pokemon-profiles-capstone.git](https://st1.zoom.us/web_client/1ej0z6i/html/externalLinkPage.html?ref=https://github.com/Alexr16/Pokemon-profiles-capstone.git)

**Comment by omar-labana** [comment]
Hi team, 

Excellent work so far! 👌
You have implemented almost all the required features and you board is complete. ✔️ 
There are some cases that you need to adjust but you are almost done! 😀

## Required Changes ♻️
- [ ] Each card should be assigned to a team member. Currently, all card have an assignee status of `No one assigned`. Kindly update your project board.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Alexr16** [comment]
Thanks for your feedback. The cards have been assigned correctly now.
